name: deploy my lambda Function

on: 
  push:
    branches: 
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.12
      - name: Install librairies
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt]; then pip install -r requirements.txt -t .;fi
      - name: zip bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: archive
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
          
          
